apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  mongodb-uri: bW9uZ29kYitzcnY6Ly9zaGFtaW11aGFtbWFkNzc6aGVsbG9BaHRpc2hhbUBtb25nb2RiOjI3MDE3L1VNUz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=  # Base64 encoded connection string with internal service
  jwt-secret: eW91cl9qd3Rfc2VjcmV0  # Base64 encoded 'your_jwt_secret'
  stripe-secret-key: c2tfdGVzdF9wbGFjZWhvbGRlcg==  # Base64 encoded 'sk_test_placeholder'