version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shamimuhammad77
      - MONGO_INITDB_ROOT_PASSWORD=helloAhtisham
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: ums-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://shamimuhammad77:helloAhtisham@cluster1.yvtj5.mongodb.net/UMS?retryWrites=true&w=majority&appName=Cluster0
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret
      - STRIPE_SECRET_KEY=sk_test_placeholder
      - CORS_ORIGIN=http://localhost:5000
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: ums-frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_URL=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local