apiVersion: v1
kind: Service
metadata:
  name: ums-frontend
  labels:
    app: ums-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: ums-frontend