apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  mongo-root-username: c2hhbWltdWhhbW1hZDc3  # Base64 encoded 'shamimuhammad77'
  mongo-root-password: aGVsbG9BaHRpc2hhbQ==  # Base64 encoded 'helloAhtisham'