name: Build and Deploy to Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create needed directories
      run: |
        # Create frontend/public if it doesn't exist
        mkdir -p app/frontend/public
        
        # Create a simple index.html if needed
        if [ ! -f app/frontend/public/index.html ]; then
          echo '<!DOCTYPE html><html><head><title>UMS</title></head><body><div id="root"></div></body></html>' > app/frontend/public/index.html
        fi
      shell: bash
        
    - name: Set up Minikube Docker environment
      run: eval $(minikube -p minikube docker-env)
      shell: bash
        
    - name: Build Backend Docker image
      run: docker build -t ahtisham05/ums-backend:latest -f backend.Dockerfile .
      shell: bash
        
    - name: Build Frontend Docker image
      run: docker build -t ahtisham05/ums-frontend:latest -f frontend.Dockerfile .
      shell: bash
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push Docker images
      run: |
        docker push ahtisham05/ums-backend:latest
        docker push ahtisham05/ums-frontend:latest
      shell: bash
        
    - name: Verify Minikube status
      run: minikube status
      shell: bash
        
    - name: Create namespace
      run: kubectl create namespace ums-system --dry-run=client -o yaml | kubectl apply -f -
      shell: bash
        
    - name: Deploy using Kustomize
      run: kubectl apply -k k8s/
      shell: bash
        
    - name: Wait for deployments
      run: |
        echo "Waiting for backend deployment..."
        kubectl -n ums-system wait --for=condition=available deployment/ums-backend --timeout=180s || true
        
        echo "Waiting for frontend deployment..."
        kubectl -n ums-system wait --for=condition=available deployment/ums-frontend --timeout=180s || true
        
        echo "Waiting for MongoDB deployment..."
        kubectl -n ums-system wait --for=condition=available deployment/mongodb --timeout=180s || true
      shell: bash
        
    - name: Show deployed resources
      run: kubectl get all -n ums-system
      shell: bash
        
    - name: Display service URL
      run: |
        echo "Frontend service is accessible at:"
        minikube service ums-frontend -n ums-system --url
      shell: bash