name: Build and Deploy to Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker to use Minikube's environment
      run: |
        eval $(minikube -p minikube docker-env)
      shell: powershell
      
    - name: Build Backend Docker image
      run: |
        docker build -t ahtisham05/university-management-system-backend:latest -f backend.Dockerfile .
      shell: powershell
      
    - name: Build Frontend Docker image
      run: |
        docker build -t ahtisham05/university-management-system-frontend:latest -f frontend.Dockerfile .
      shell: powershell
      
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      shell: powershell
      
    - name: Push Docker images
      run: |
        docker push ahtisham05/university-management-system-backend:latest
        docker push ahtisham05/university-management-system-frontend:latest
      shell: powershell
      
    - name: Create namespace if not exists
      run: |
        kubectl create namespace ums-system --dry-run=client -o yaml | kubectl apply -f -
      shell: powershell
      
    - name: Deploy to Minikube
      run: |
        kubectl apply -k k8s/
      shell: powershell
      
    - name: Show deployed resources
      run: |
        kubectl get all -n ums-system
      shell: powershell